import type { BuildingDef } from '../buildingTypes';

export const BUILDING_DEFS: BuildingDef[] = [
	{
		id: 'sword_barracks',
		name: 'Swordsman Barracks',
		description: 'Melee fighters with decent stats.',
		textureId: 'building_sword_barracks',
		assetPath: 'game_icons/sword-brandish.svg',
		cost: { wood: 50, stone: 100 },
		buildTime: 2,
		army: {
			unitId: 'swordsman',
			trainCostBase: { wood: 50, stone: 25 },
			trainCostMult: 1.5,
			trainTime: 5,
			trainDef: { health: 20, attackDamage: 5, drFlat: 1 },
		},
	},
	{
		id: 'archer_range',
		name: 'Archery Range',
		description: 'Ranged low-health fighters, aiming for the army\'s back.',
		textureId: 'building_archer_range',
		assetPath: 'game_icons/high-shot.svg',
		cost: { wood: 120, stone: 40 },
		buildTime: 3,
		army: {
			unitId: 'archer',
			trainCostBase: { wood: 30, stone: 10 },
			trainCostMult: 1.25,
			trainTime: 4,
			trainDef: { health: 5, attackDamage: 5, drFlat: 0 },
		},
	},
	{
		id: 'defender_hideout',
		name: 'Defender Hideout',
		description: 'Slow-attacking, but armored defenders.',
		textureId: 'building_defender_hideout',
		assetPath: 'game_icons/vibrating-shield.svg',
		cost: { wood: 50, stone: 50 },
		buildTime: 4,
		army: {
			unitId: 'defender',
			trainCostBase: { wood: 40, stone: 60 },
			trainCostMult: 1.4,
			trainTime: 6,
			trainDef: { health: 50, attackDamage: 1, drFlat: 5 },
		},
	},
	{
		id: 'earth_mage_tower',
		name: 'Earth Mage Tower',
		description: 'Earth mages create shockwaves, damaging all enemies.',
		textureId: 'building_earth_mage_tower',
		assetPath: 'game_icons/earth-crack.svg',
		cost: { wood: 80, stone: 150, mana: 10 },
		buildTime: 5,
		army: {
			unitId: 'earth_mage',
			trainCostBase: { wood: 70, stone: 80, mana: 5 },
			trainCostMult: 1.6,
			trainTime: 8,
			trainDef: { health: 10, attackDamage: 10, drFlat: 0 },
		},
	},
	{
		id: 'magic_archer_training_ground',
		name: 'Magic Archer Training Ground',
		description: 'Magic archers shoot twice, at a first and last army unit.',
		textureId: 'building_magic_archer_training_ground',
		assetPath: 'game_icons/double-shot.svg',
		cost: { wood: 150, stone: 100, mana: 20 },
		buildTime: 6,
		army: {
			unitId: 'magic_archer',
			trainCostBase: { wood: 100, stone: 50, mana: 10 },
			trainCostMult: 1.7,
			trainTime: 7,
			trainDef: { health: 15, attackDamage: 7, drFlat: 2 },
		},
	},
	{
		id: 'crossbow_range',
		name: 'Crossbowman Range',
		description: 'Improved ranged units shower 3 bolts on the frontline every turn.',
		textureId: 'building_crossbow_range',
		assetPath: 'game_icons/crossbow.svg',
		cost: { wood: 100, stone: 80 },
		buildTime: 4,
		army: {
			unitId: 'crossbowman',
			trainCostBase: { wood: 40, stone: 30 },
			trainCostMult: 1.5,
			trainTime: 5,
			trainDef: { health: 0, attackDamage: 5, drFlat: 0 },
		},
	},
	{
		id: 'assassin_guild',
		name: 'Assassin Guild',
		description: 'Stealthy units striking the lowest health enemy unit.',
		textureId: 'building_assassin_guild',
		assetPath: 'game_icons/backstab.svg',
		cost: { wood: 80, stone: 60, mana: 15 },
		buildTime: 5,
		army: {
			unitId: 'assassin',
			trainCostBase: { wood: 30, stone: 20, mana: 5 },
			trainCostMult: 2,
			trainTime: 4,
			trainDef: { health: 2, attackDamage: 3, drFlat: 0 },
		},
	},
	{
		id: 'death_mage_tower',
		name: 'Death Mage Tower',
		description: 'Death mages take 5 turns to prepare, then instakill the first enemy.',
		textureId: 'building_death_mage_tower',
		assetPath: 'game_icons/disintegrate.svg',
		cost: { wood: 100, stone: 30, mana: 100 },
		buildTime: 5,
		army: {
			unitId: 'death_mage',
			trainCostBase: { mana: 10 },
			trainCostMult: 2,
			trainTime: 10,
			trainDef: { health: 50, attackDamage: 0, drFlat: 0 },
		},
	},
	{
		id: 'champion_arena',
		name: 'Champion Arena',
		description: 'Versatile fighters, switching attack styles each turn.',
		textureId: 'building_champion_arena',
		assetPath: 'game_icons/brutal-helm.svg',
		cost: { wood: 150, stone: 150 },
		buildTime: 6,
		army: {
			unitId: 'champion',
			trainCostBase: { wood: 150, stone: 150 },
			trainCostMult: 1.1,
			trainTime: 10,
			trainDef: { health: 20, attackDamage: 2, drFlat: 2 },
		},
	},
];
